### ISSUE TITLE
Question:  Terraform State & github actions

### ISSUE THREAD

**Issue by mike-leuer** [PerfectThymeTech/terraform-azurerm-data-landing-zone#26]
### Feature or Idea - What?

I know this is a new project. But I wanted to get an understanding of where you plan on keeping the state?

### Feature or Idea - Why?

Above.

**Comment by marvinbuss** [comment]
@mike-leuer thanks for your question. It is up to you to decide where you want to store the state file. [Many viable backend options are available and can be used.](https://developer.hashicorp.com/terraform/language/settings/backends/configuration#available-backends)

I would recommend using a remote location like Azure Storage or Terraform Cloud in order to be able to collaborate with other team members. I generally use Azure Storage as part of the e2e tests and any of my other projects.

**Comment by mike-leuer** [comment]
Thank you, we most likely use Azure Storage. Could you add documentation on how you store it using github actions and azure storage? It would be helpful to learn when the time comes.

I see here how it is created locally to storage but not using github,
https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=terraform

**Comment by marvinbuss** [comment]
@mike-leuer do you have any follow-up questions or can I close this issue?

**Comment by marvinbuss** [comment]
Closing this because of no further updates. Please re-open in case I missed any questions.
