### ISSUE TITLE
Bug: databricks_group referenced but never created

### ISSUE THREAD

**Issue by opme** [PerfectThymeTech/terraform-azurerm-data-landing-zone#57]
### Steps to reproduce

Deployed the module and terraform apply almost goes through.  There is a data block referencing a group that was never created.  I have defined databricks_admin_groupname as an existing aad group name in tfvars.  Not sure how this should work.

./modules/databricksconfiguration/data.tf

```
data "databricks_group" "group" {
  count        = var.databricks_admin_groupname != "" ? 1 : 0
  display_name = var.databricks_admin_groupname
  provider = databricks.account
}
```

**Comment by marvinbuss** [comment]
Thanks @opme . I will review this tomorrow or on the weekend.

**Comment by marvinbuss** [comment]
Hi @opme, Sorry for the late response. Yes, you are right. This variable expects you to provide the name of an Azure Databricks account group (from [https://accounts.azuredatabricks.net/](https://accounts.azuredatabricks.net/)). The module is not creating the group as many customers actually want to use the [SCIM sync from Entry ID](https://learn.microsoft.com/en-us/azure/databricks/administration-guide/users-groups/scim/aad) instead of having to manage bespoke groups in the Databricks account level.

Are you sure that the SP requires Azure Databricks Account Admin permissions?
I will have to validate that and update the docs accordingly. It certainly needs to be synced and added to the account level and it also needs to be granted some permissions as documented here:
https://github.com/PerfectThymeTech/terraform-azurerm-data-landing-zone?tab=readme-ov-file#prerequisites

**Comment by marvinbuss** [comment]
@opme I just updated the docs in the linked PR. Any suggestions how to make this more clear?
I also have to validate the required permissions once more.

**Comment by marvinbuss** [comment]
You are right that this feature requires Databricks Account Admin rights today. I added this to the docs. Please provide feedback. Thanks!
